export const GET_PRODUCTS_BASKET = "GET_PRODUCTS_BASKET";

export const GET_PRODUCT_BASKET = "GET_PRODUCT_BASKET";

export const ADED_PRODUCT_BASKET = "ADED_PRODUCT_BASKET";

export const EDIT_PRODUCT_BASKET = "EDIT_PRODUCT_BASKET";

export const DELETE_PRODUCT_BASKET = "DELETE_PRODUCT_BASKET";
