export const GET_PRODUCTS = "GET_PRODUCTS";

export const GET_PRODUCT = "GET_PRODUCT";

export const ADED_PRODUCTS = "ADED_PRODUCTS";

export const EDIT_PRODUCTS = "EDIT_PRODUCTS";

export const DELETE_PRODUCTS = "DELETE_PRODUCTS";
